/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ekf_fuse_baro_10state_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {1, 1, 1};
static const casadi_int casadi_s1[3] = {10, 1, 1};
static const casadi_int casadi_s2[3] = {10, 10, 1};

/* ekf_fuse_baro:(i0,i1,i2[10],i3[10x10])->(o0[10],o1[10x10],o2,o3[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  a00=arg[2]? arg[2][0] : 0;
  a01=arg[3]? arg[3][20] : 0;
  a02=arg[3]? arg[3][22] : 0;
  a03=arg[1]? arg[1][0] : 0;
  a03=(a02+a03);
  a04=(a01/a03);
  a05=arg[0]? arg[0][0] : 0;
  a06=arg[2]? arg[2][2] : 0;
  a05=(a05-a06);
  a07=(a04*a05);
  a00=(a00+a07);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[2]? arg[2][1] : 0;
  a07=arg[3]? arg[3][21] : 0;
  a08=(a07/a03);
  a09=(a08*a05);
  a00=(a00+a09);
  if (res[0]!=0) res[0][1]=a00;
  a00=(a02/a03);
  a09=(a00*a05);
  a06=(a06+a09);
  if (res[0]!=0) res[0][2]=a06;
  a06=arg[2]? arg[2][3] : 0;
  a09=arg[3]? arg[3][23] : 0;
  a10=(a09/a03);
  a11=(a10*a05);
  a06=(a06+a11);
  if (res[0]!=0) res[0][3]=a06;
  a06=arg[2]? arg[2][4] : 0;
  a11=arg[3]? arg[3][24] : 0;
  a12=(a11/a03);
  a13=(a12*a05);
  a06=(a06+a13);
  if (res[0]!=0) res[0][4]=a06;
  a06=arg[2]? arg[2][5] : 0;
  a13=arg[3]? arg[3][25] : 0;
  a14=(a13/a03);
  a15=(a14*a05);
  a06=(a06+a15);
  if (res[0]!=0) res[0][5]=a06;
  a06=arg[2]? arg[2][6] : 0;
  a15=arg[3]? arg[3][26] : 0;
  a16=(a15/a03);
  a17=(a16*a05);
  a06=(a06+a17);
  if (res[0]!=0) res[0][6]=a06;
  a06=arg[2]? arg[2][7] : 0;
  a17=arg[3]? arg[3][27] : 0;
  a18=(a17/a03);
  a19=(a18*a05);
  a06=(a06+a19);
  if (res[0]!=0) res[0][7]=a06;
  a06=arg[2]? arg[2][8] : 0;
  a19=arg[3]? arg[3][28] : 0;
  a20=(a19/a03);
  a21=(a20*a05);
  a06=(a06+a21);
  if (res[0]!=0) res[0][8]=a06;
  a06=arg[2]? arg[2][9] : 0;
  a21=arg[3]? arg[3][29] : 0;
  a03=(a21/a03);
  a22=(a03*a05);
  a06=(a06+a22);
  if (res[0]!=0) res[0][9]=a06;
  a06=arg[3]? arg[3][0] : 0;
  a22=arg[3]? arg[3][2] : 0;
  a23=(a04*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][0]=a06;
  a06=arg[3]? arg[3][1] : 0;
  a23=(a08*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][1]=a06;
  a06=(a00*a22);
  a06=(a22-a06);
  if (res[1]!=0) res[1][2]=a06;
  a06=arg[3]? arg[3][3] : 0;
  a23=(a10*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][3]=a06;
  a06=arg[3]? arg[3][4] : 0;
  a23=(a12*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][4]=a06;
  a06=arg[3]? arg[3][5] : 0;
  a23=(a14*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][5]=a06;
  a06=arg[3]? arg[3][6] : 0;
  a23=(a16*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][6]=a06;
  a06=arg[3]? arg[3][7] : 0;
  a23=(a18*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][7]=a06;
  a06=arg[3]? arg[3][8] : 0;
  a23=(a20*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][8]=a06;
  a06=arg[3]? arg[3][9] : 0;
  a22=(a03*a22);
  a06=(a06-a22);
  if (res[1]!=0) res[1][9]=a06;
  a06=arg[3]? arg[3][10] : 0;
  a22=arg[3]? arg[3][12] : 0;
  a23=(a04*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][10]=a06;
  a06=arg[3]? arg[3][11] : 0;
  a23=(a08*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][11]=a06;
  a06=(a00*a22);
  a06=(a22-a06);
  if (res[1]!=0) res[1][12]=a06;
  a06=arg[3]? arg[3][13] : 0;
  a23=(a10*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][13]=a06;
  a06=arg[3]? arg[3][14] : 0;
  a23=(a12*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][14]=a06;
  a06=arg[3]? arg[3][15] : 0;
  a23=(a14*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][15]=a06;
  a06=arg[3]? arg[3][16] : 0;
  a23=(a16*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][16]=a06;
  a06=arg[3]? arg[3][17] : 0;
  a23=(a18*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][17]=a06;
  a06=arg[3]? arg[3][18] : 0;
  a23=(a20*a22);
  a06=(a06-a23);
  if (res[1]!=0) res[1][18]=a06;
  a06=arg[3]? arg[3][19] : 0;
  a22=(a03*a22);
  a06=(a06-a22);
  if (res[1]!=0) res[1][19]=a06;
  a06=(a04*a02);
  a01=(a01-a06);
  if (res[1]!=0) res[1][20]=a01;
  a01=(a08*a02);
  a07=(a07-a01);
  if (res[1]!=0) res[1][21]=a07;
  a07=(a00*a02);
  a07=(a02-a07);
  if (res[1]!=0) res[1][22]=a07;
  a07=(a10*a02);
  a09=(a09-a07);
  if (res[1]!=0) res[1][23]=a09;
  a09=(a12*a02);
  a11=(a11-a09);
  if (res[1]!=0) res[1][24]=a11;
  a11=(a14*a02);
  a13=(a13-a11);
  if (res[1]!=0) res[1][25]=a13;
  a13=(a16*a02);
  a15=(a15-a13);
  if (res[1]!=0) res[1][26]=a15;
  a15=(a18*a02);
  a17=(a17-a15);
  if (res[1]!=0) res[1][27]=a17;
  a17=(a20*a02);
  a19=(a19-a17);
  if (res[1]!=0) res[1][28]=a19;
  a02=(a03*a02);
  a21=(a21-a02);
  if (res[1]!=0) res[1][29]=a21;
  a21=arg[3]? arg[3][30] : 0;
  a02=arg[3]? arg[3][32] : 0;
  a19=(a04*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][30]=a21;
  a21=arg[3]? arg[3][31] : 0;
  a19=(a08*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][31]=a21;
  a21=(a00*a02);
  a21=(a02-a21);
  if (res[1]!=0) res[1][32]=a21;
  a21=arg[3]? arg[3][33] : 0;
  a19=(a10*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][33]=a21;
  a21=arg[3]? arg[3][34] : 0;
  a19=(a12*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][34]=a21;
  a21=arg[3]? arg[3][35] : 0;
  a19=(a14*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][35]=a21;
  a21=arg[3]? arg[3][36] : 0;
  a19=(a16*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][36]=a21;
  a21=arg[3]? arg[3][37] : 0;
  a19=(a18*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][37]=a21;
  a21=arg[3]? arg[3][38] : 0;
  a19=(a20*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][38]=a21;
  a21=arg[3]? arg[3][39] : 0;
  a02=(a03*a02);
  a21=(a21-a02);
  if (res[1]!=0) res[1][39]=a21;
  a21=arg[3]? arg[3][40] : 0;
  a02=arg[3]? arg[3][42] : 0;
  a19=(a04*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][40]=a21;
  a21=arg[3]? arg[3][41] : 0;
  a19=(a08*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][41]=a21;
  a21=(a00*a02);
  a21=(a02-a21);
  if (res[1]!=0) res[1][42]=a21;
  a21=arg[3]? arg[3][43] : 0;
  a19=(a10*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][43]=a21;
  a21=arg[3]? arg[3][44] : 0;
  a19=(a12*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][44]=a21;
  a21=arg[3]? arg[3][45] : 0;
  a19=(a14*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][45]=a21;
  a21=arg[3]? arg[3][46] : 0;
  a19=(a16*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][46]=a21;
  a21=arg[3]? arg[3][47] : 0;
  a19=(a18*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][47]=a21;
  a21=arg[3]? arg[3][48] : 0;
  a19=(a20*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][48]=a21;
  a21=arg[3]? arg[3][49] : 0;
  a02=(a03*a02);
  a21=(a21-a02);
  if (res[1]!=0) res[1][49]=a21;
  a21=arg[3]? arg[3][50] : 0;
  a02=arg[3]? arg[3][52] : 0;
  a19=(a04*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][50]=a21;
  a21=arg[3]? arg[3][51] : 0;
  a19=(a08*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][51]=a21;
  a21=(a00*a02);
  a21=(a02-a21);
  if (res[1]!=0) res[1][52]=a21;
  a21=arg[3]? arg[3][53] : 0;
  a19=(a10*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][53]=a21;
  a21=arg[3]? arg[3][54] : 0;
  a19=(a12*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][54]=a21;
  a21=arg[3]? arg[3][55] : 0;
  a19=(a14*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][55]=a21;
  a21=arg[3]? arg[3][56] : 0;
  a19=(a16*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][56]=a21;
  a21=arg[3]? arg[3][57] : 0;
  a19=(a18*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][57]=a21;
  a21=arg[3]? arg[3][58] : 0;
  a19=(a20*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][58]=a21;
  a21=arg[3]? arg[3][59] : 0;
  a02=(a03*a02);
  a21=(a21-a02);
  if (res[1]!=0) res[1][59]=a21;
  a21=arg[3]? arg[3][60] : 0;
  a02=arg[3]? arg[3][62] : 0;
  a19=(a04*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][60]=a21;
  a21=arg[3]? arg[3][61] : 0;
  a19=(a08*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][61]=a21;
  a21=(a00*a02);
  a21=(a02-a21);
  if (res[1]!=0) res[1][62]=a21;
  a21=arg[3]? arg[3][63] : 0;
  a19=(a10*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][63]=a21;
  a21=arg[3]? arg[3][64] : 0;
  a19=(a12*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][64]=a21;
  a21=arg[3]? arg[3][65] : 0;
  a19=(a14*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][65]=a21;
  a21=arg[3]? arg[3][66] : 0;
  a19=(a16*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][66]=a21;
  a21=arg[3]? arg[3][67] : 0;
  a19=(a18*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][67]=a21;
  a21=arg[3]? arg[3][68] : 0;
  a19=(a20*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][68]=a21;
  a21=arg[3]? arg[3][69] : 0;
  a02=(a03*a02);
  a21=(a21-a02);
  if (res[1]!=0) res[1][69]=a21;
  a21=arg[3]? arg[3][70] : 0;
  a02=arg[3]? arg[3][72] : 0;
  a19=(a04*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][70]=a21;
  a21=arg[3]? arg[3][71] : 0;
  a19=(a08*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][71]=a21;
  a21=(a00*a02);
  a21=(a02-a21);
  if (res[1]!=0) res[1][72]=a21;
  a21=arg[3]? arg[3][73] : 0;
  a19=(a10*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][73]=a21;
  a21=arg[3]? arg[3][74] : 0;
  a19=(a12*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][74]=a21;
  a21=arg[3]? arg[3][75] : 0;
  a19=(a14*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][75]=a21;
  a21=arg[3]? arg[3][76] : 0;
  a19=(a16*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][76]=a21;
  a21=arg[3]? arg[3][77] : 0;
  a19=(a18*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][77]=a21;
  a21=arg[3]? arg[3][78] : 0;
  a19=(a20*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][78]=a21;
  a21=arg[3]? arg[3][79] : 0;
  a02=(a03*a02);
  a21=(a21-a02);
  if (res[1]!=0) res[1][79]=a21;
  a21=arg[3]? arg[3][80] : 0;
  a02=arg[3]? arg[3][82] : 0;
  a19=(a04*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][80]=a21;
  a21=arg[3]? arg[3][81] : 0;
  a19=(a08*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][81]=a21;
  a21=(a00*a02);
  a21=(a02-a21);
  if (res[1]!=0) res[1][82]=a21;
  a21=arg[3]? arg[3][83] : 0;
  a19=(a10*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][83]=a21;
  a21=arg[3]? arg[3][84] : 0;
  a19=(a12*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][84]=a21;
  a21=arg[3]? arg[3][85] : 0;
  a19=(a14*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][85]=a21;
  a21=arg[3]? arg[3][86] : 0;
  a19=(a16*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][86]=a21;
  a21=arg[3]? arg[3][87] : 0;
  a19=(a18*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][87]=a21;
  a21=arg[3]? arg[3][88] : 0;
  a19=(a20*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][88]=a21;
  a21=arg[3]? arg[3][89] : 0;
  a02=(a03*a02);
  a21=(a21-a02);
  if (res[1]!=0) res[1][89]=a21;
  a21=arg[3]? arg[3][90] : 0;
  a02=arg[3]? arg[3][92] : 0;
  a19=(a04*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][90]=a21;
  a21=arg[3]? arg[3][91] : 0;
  a19=(a08*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][91]=a21;
  a21=(a00*a02);
  a21=(a02-a21);
  if (res[1]!=0) res[1][92]=a21;
  a21=arg[3]? arg[3][93] : 0;
  a19=(a10*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][93]=a21;
  a21=arg[3]? arg[3][94] : 0;
  a19=(a12*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][94]=a21;
  a21=arg[3]? arg[3][95] : 0;
  a19=(a14*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][95]=a21;
  a21=arg[3]? arg[3][96] : 0;
  a19=(a16*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][96]=a21;
  a21=arg[3]? arg[3][97] : 0;
  a19=(a18*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][97]=a21;
  a21=arg[3]? arg[3][98] : 0;
  a19=(a20*a02);
  a21=(a21-a19);
  if (res[1]!=0) res[1][98]=a21;
  a21=arg[3]? arg[3][99] : 0;
  a02=(a03*a02);
  a21=(a21-a02);
  if (res[1]!=0) res[1][99]=a21;
  if (res[2]!=0) res[2][0]=a05;
  if (res[3]!=0) res[3][0]=a04;
  if (res[3]!=0) res[3][1]=a08;
  if (res[3]!=0) res[3][2]=a00;
  if (res[3]!=0) res[3][3]=a10;
  if (res[3]!=0) res[3][4]=a12;
  if (res[3]!=0) res[3][5]=a14;
  if (res[3]!=0) res[3][6]=a16;
  if (res[3]!=0) res[3][7]=a18;
  if (res[3]!=0) res[3][8]=a20;
  if (res[3]!=0) res[3][9]=a03;
  return 0;
}

CASADI_SYMBOL_EXPORT int ekf_fuse_baro(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ekf_fuse_baro_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ekf_fuse_baro_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ekf_fuse_baro_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ekf_fuse_baro_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ekf_fuse_baro_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ekf_fuse_baro_incref(void) {
}

CASADI_SYMBOL_EXPORT void ekf_fuse_baro_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ekf_fuse_baro_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ekf_fuse_baro_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real ekf_fuse_baro_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ekf_fuse_baro_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ekf_fuse_baro_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ekf_fuse_baro_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ekf_fuse_baro_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ekf_fuse_baro_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ekf_fuse_baro_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
