/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ekf_correct_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real float
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[12] = 
  {0, 4, 8, 12, 16, 20, 24, 25,
  26, 27, 28, 29};
static const casadi_int casadi_s1[135] = 
  {10, 12, 0, 10, 20, 30, 40, 50,
  60, 70, 80, 90, 100, 110, 120, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s2[45] = 
  {10, 12, 0, 4, 8, 12, 16, 20,
  24, 25, 26, 27, 28, 29, 30, 6,
  7, 8, 9, 6, 7, 8, 9, 6,
  7, 8, 9, 6, 7, 8, 9, 6,
  7, 8, 9, 6, 7, 8, 9, 0,
  1, 2, 3, 4, 5};
static const casadi_int casadi_s3[113] = 
  {10, 10, 0, 10, 20, 30, 40, 50,
  60, 70, 80, 90, 100, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9};
static const casadi_int casadi_s4[43] = 
  {12, 10, 0, 1, 2, 3, 4, 5,
  6, 12, 18, 24, 30, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5, 0, 1, 2,
  3, 4, 5};
static const casadi_int casadi_s5[133] = 
  {12, 10, 0, 12, 24, 36, 48, 60,
  72, 84, 96, 108, 120, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11};
static const casadi_int casadi_s6[159] = 
  {12, 12, 0, 12, 24, 36, 48, 60,
  72, 84, 96, 108, 120, 132, 144, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[36] = 
  {12, 3, 0, 10, 20, 30, 0, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  1, 3, 4, 5, 6, 7, 8, 9,
  10, 11, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11};
static const casadi_int casadi_s9[45] = 
  {3, 12, 0, 1, 2, 3, 6, 9,
  12, 15, 18, 21, 24, 27, 30, 0,
  1, 2, 0, 1, 2, 0, 1, 2,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2};
static const casadi_int casadi_s10[36] = 
  {12, 3, 0, 10, 20, 30, 0, 1,
  2, 3, 6, 7, 8, 9, 10, 11,
  0, 1, 2, 4, 6, 7, 8, 9,
  10, 11, 0, 1, 2, 5, 6, 7,
  8, 9, 10, 11};
static const casadi_int casadi_s11[45] = 
  {3, 12, 0, 3, 6, 9, 10, 11,
  12, 15, 18, 21, 24, 27, 30, 0,
  1, 2, 0, 1, 2, 0, 1, 2,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2};
static const casadi_int casadi_s12[36] = 
  {12, 3, 0, 10, 20, 30, 0, 1,
  2, 3, 4, 5, 6, 9, 10, 11,
  0, 1, 2, 3, 4, 5, 7, 9,
  10, 11, 0, 1, 2, 3, 4, 5,
  8, 9, 10, 11};
static const casadi_int casadi_s13[45] = 
  {3, 12, 0, 3, 6, 9, 12, 15,
  18, 19, 20, 21, 24, 27, 30, 0,
  1, 2, 0, 1, 2, 0, 1, 2,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2};
static const casadi_int casadi_s14[36] = 
  {12, 3, 0, 10, 20, 30, 0, 1,
  2, 3, 4, 5, 6, 7, 8, 9,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 10, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 11};
static const casadi_int casadi_s15[45] = 
  {3, 12, 0, 3, 6, 9, 12, 15,
  18, 21, 24, 27, 28, 29, 30, 0,
  1, 2, 0, 1, 2, 0, 1, 2,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2};
static const casadi_int casadi_s16[135] = 
  {12, 12, 0, 10, 20, 30, 40, 50,
  60, 70, 80, 90, 100, 110, 120, 0,
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 1, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 0, 1, 2,
  3, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 4, 6, 7, 8, 9, 10,
  11, 0, 1, 2, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 9, 10, 11, 0, 1, 2,
  3, 4, 5, 7, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 8, 9, 10,
  11, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 10, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 11};
static const casadi_int casadi_s17[12] = 
  {0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11};
static const casadi_int casadi_s18[93] = 
  {12, 12, 0, 12, 23, 33, 42, 50,
  57, 63, 68, 72, 75, 77, 78, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 4, 5, 6, 7, 8, 9, 10,
  11, 5, 6, 7, 8, 9, 10, 11,
  6, 7, 8, 9, 10, 11, 7, 8,
  9, 10, 11, 8, 9, 10, 11, 9,
  10, 11, 10, 11, 11};
static const casadi_int casadi_s19[93] = 
  {12, 12, 0, 1, 3, 6, 10, 15,
  21, 28, 36, 45, 55, 66, 78, 0,
  0, 1, 0, 1, 2, 0, 1, 2,
  3, 0, 1, 2, 3, 4, 0, 1,
  2, 3, 4, 5, 0, 1, 2, 3,
  4, 5, 6, 0, 1, 2, 3, 4,
  5, 6, 7, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 0, 1,
  2, 3, 4, 5, 6, 7, 8, 9,
  10, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11};
static const casadi_int casadi_s20[3] = {10, 1, 1};
static const casadi_int casadi_s21[3] = {10, 10, 1};
static const casadi_int casadi_s22[3] = {3, 1, 1};
static const casadi_int casadi_s23[3] = {1, 1, 1};
static const casadi_int casadi_s24[3] = {12, 1, 1};
static const casadi_int casadi_s25[3] = {10, 12, 1};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 3.7460659341591196e-01, 9.2718385456678742e-01};
static const casadi_real casadi_c2[144] = 
  {1., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 1., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 1., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 1.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 1., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 1., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 1., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 1., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  1., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 1., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 1., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 1.};

static const casadi_real casadi_zeros[100] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* ekf_correct:(i0[10],i1[10x10],i2[3],i3,i4[3],i5,i6[3],i7[3],i8,i9)->(o0[10],o1[10x10],o2[12],o3[10x12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+12, *w01=w+22, *w02=w+32, *w03=w+152, *w04=w+272, *w05=w+372, *w06=w+402, w07, w08, w09, w10;
  casadi_real w11, w12, *w13=w+411, w14, w15, w16, *w17=w+417, w18, w19, w20, *w21=w+423, *w22=w+426;
  casadi_real *w23=w+435, *w24=w+438, *w25=w+441, w26, w27, w28, w29, w30, w31, w32, w33, w34;
  casadi_real *w37=w+462, *w38=w+468, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48;
  casadi_real w49, w50, w51, w52, w53, w54, w55, w56, *w57=w+492, *w58=w+636, *w59=w+780, *w60=w+900;
  casadi_real *w61=w+930, *w62=w+957, *w63=w+987, *w64=w+1005, *w65=w+1035, *w66=w+1065, *w67=w+1095, *w68=w+1215, *w69=w+1359, *w70=w+1371, *w71=w+1471;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *ss, *wr00, *wr04, *wr17, *wr21, *wr57;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = zeros(10x1) */
  casadi_clear(w01, 10);
  /* #2: @2 = zeros(10x12) */
  casadi_clear(w02, 120);
  /* #3: @3 = zeros(10x12) */
  casadi_clear(w03, 120);
  /* #4: @4 = input[1][0] */
  wr04 = arg[1] ? arg[1] : casadi_zeros;
  /* #5: @5 = zeros(10x12,30nz) */
  casadi_clear(w05, 30);
  /* #6: @6 = zeros(3x1) */
  casadi_clear(w06, 3);
  /* #7: @7 = @0[6] */
  w07 = wr00[6];
  /* #8: @8 = (2.*@7) */
  w08 = (2.* w07 );
  /* #9: @9 = @0[9] */
  w09 = wr00[9];
  /* #10: @10 = (-@9) */
  w10 = (- w09 );
  /* #11: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #12: @11 = @0[8] */
  w11 = wr00[8];
  /* #13: @12 = (2.*@11) */
  w12 = (2.* w11 );
  /* #14: @13 = horzcat(@8, @10, @12) */
  rr=w13;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w12;
  /* #15: @13 = @13' */
  /* #16: @8 = @0[9] */
  w08 = wr00[9];
  /* #17: @10 = (2.*@8) */
  w10 = (2.* w08 );
  /* #18: @12 = @0[6] */
  w12 = wr00[6];
  /* #19: @14 = (2.*@12) */
  w14 = (2.* w12 );
  /* #20: @15 = @0[7] */
  w15 = wr00[7];
  /* #21: @16 = (-@15) */
  w16 = (- w15 );
  /* #22: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #23: @17 = horzcat(@10, @14, @16) */
  rr=w17;
  *rr++ = w10;
  *rr++ = w14;
  *rr++ = w16;
  /* #24: @17 = @17' */
  /* #25: @10 = @0[8] */
  w10 = wr00[8];
  /* #26: @14 = (-@10) */
  w14 = (- w10 );
  /* #27: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #28: @16 = @0[7] */
  w16 = wr00[7];
  /* #29: @18 = (2.*@16) */
  w18 = (2.* w16 );
  /* #30: @19 = @0[6] */
  w19 = wr00[6];
  /* #31: @20 = (2.*@19) */
  w20 = (2.* w19 );
  /* #32: @21 = horzcat(@14, @18, @20) */
  rr=w21;
  *rr++ = w14;
  *rr++ = w18;
  *rr++ = w20;
  /* #33: @21 = @21' */
  /* #34: @22 = horzcat(@13, @17, @21) */
  rr=w22;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #35: @13 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w13);
  /* #36: @6 = mac(@22,@13,@6) */
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w13+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #37: @17 = zeros(3x1) */
  casadi_clear(w17, 3);
  /* #38: @21 = [0, 0.374607, 0.927184] */
  casadi_copy(casadi_c1, 3, w21);
  /* #39: @17 = mac(@22,@21,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #40: @23 = ones(3x1) */
  casadi_fill(w23, 3, 1.);
  /* #41: @24 = ones(3x1) */
  casadi_fill(w24, 3, 1.);
  /* #42: @25 = vertcat(@6, @17, @23, @24) */
  rr=w25;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #43: (@5[0, 4, 8, 12, 16, 20, 24, 25, 26, 27, 28, 29] = @25) */
  for (cii=casadi_s0, rr=w05, cs=w25; cii!=casadi_s0+12; ++cii, ++cs) rr[*cii] = *cs;
  /* #44: @6 = zeros(3x1) */
  casadi_clear(w06, 3);
  /* #45: @14 = @0[7] */
  w14 = wr00[7];
  /* #46: @18 = (2.*@14) */
  w18 = (2.* w14 );
  /* #47: @20 = @0[8] */
  w20 = wr00[8];
  /* #48: @26 = (2.*@20) */
  w26 = (2.* w20 );
  /* #49: @27 = @0[9] */
  w27 = wr00[9];
  /* #50: @28 = (2.*@27) */
  w28 = (2.* w27 );
  /* #51: @17 = horzcat(@18, @26, @28) */
  rr=w17;
  *rr++ = w18;
  *rr++ = w26;
  *rr++ = w28;
  /* #52: @17 = @17' */
  /* #53: @18 = @0[8] */
  w18 = wr00[8];
  /* #54: @26 = (2.*@18) */
  w26 = (2.* w18 );
  /* #55: @28 = @0[7] */
  w28 = wr00[7];
  /* #56: @29 = (2.*@28) */
  w29 = (2.* w28 );
  /* #57: @29 = (-@29) */
  w29 = (- w29 );
  /* #58: @30 = @0[6] */
  w30 = wr00[6];
  /* #59: @31 = (-@30) */
  w31 = (- w30 );
  /* #60: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #61: @23 = horzcat(@26, @29, @31) */
  rr=w23;
  *rr++ = w26;
  *rr++ = w29;
  *rr++ = w31;
  /* #62: @23 = @23' */
  /* #63: @26 = @0[9] */
  w26 = wr00[9];
  /* #64: @29 = (2.*@26) */
  w29 = (2.* w26 );
  /* #65: @31 = @0[6] */
  w31 = wr00[6];
  /* #66: @32 = (2.*@31) */
  w32 = (2.* w31 );
  /* #67: @33 = @0[7] */
  w33 = wr00[7];
  /* #68: @34 = (2.*@33) */
  w34 = (2.* w33 );
  /* #69: @34 = (-@34) */
  w34 = (- w34 );
  /* #70: @24 = horzcat(@29, @32, @34) */
  rr=w24;
  *rr++ = w29;
  *rr++ = w32;
  *rr++ = w34;
  /* #71: @24 = @24' */
  /* #72: @22 = horzcat(@17, @23, @24) */
  rr=w22;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #73: @6 = mac(@22,@13,@6) */
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w13+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #74: @17 = zeros(3x1) */
  casadi_clear(w17, 3);
  /* #75: @17 = mac(@22,@21,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #76: @35 = zeros(3x1,0nz) */
  /* #77: @36 = zeros(3x1,0nz) */
  /* #78: @37 = vertcat(@6, @17, @35, @36) */
  rr=w37;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  /* #79: @38 = @37[:6] */
  for (rr=w38, cs=w37+0; cs!=w37+6; cs+=1) *rr++ = *cs;
  /* #80: (@5[1:25:4] = @38) */
  for (rr=w05+1, cs=w38; rr!=w05+25; rr+=4) *rr = *cs++;
  /* #81: @6 = zeros(3x1) */
  casadi_clear(w06, 3);
  /* #82: @29 = @0[8] */
  w29 = wr00[8];
  /* #83: @32 = (2.*@29) */
  w32 = (2.* w29 );
  /* #84: @32 = (-@32) */
  w32 = (- w32 );
  /* #85: @34 = @0[7] */
  w34 = wr00[7];
  /* #86: @39 = (2.*@34) */
  w39 = (2.* w34 );
  /* #87: @40 = @0[6] */
  w40 = wr00[6];
  /* #88: @41 = (2.*@40) */
  w41 = (2.* w40 );
  /* #89: @17 = horzcat(@32, @39, @41) */
  rr=w17;
  *rr++ = w32;
  *rr++ = w39;
  *rr++ = w41;
  /* #90: @17 = @17' */
  /* #91: @32 = @0[7] */
  w32 = wr00[7];
  /* #92: @39 = (2.*@32) */
  w39 = (2.* w32 );
  /* #93: @41 = @0[8] */
  w41 = wr00[8];
  /* #94: @42 = (2.*@41) */
  w42 = (2.* w41 );
  /* #95: @43 = @0[9] */
  w43 = wr00[9];
  /* #96: @44 = (2.*@43) */
  w44 = (2.* w43 );
  /* #97: @23 = horzcat(@39, @42, @44) */
  rr=w23;
  *rr++ = w39;
  *rr++ = w42;
  *rr++ = w44;
  /* #98: @23 = @23' */
  /* #99: @39 = @0[6] */
  w39 = wr00[6];
  /* #100: @42 = (-@39) */
  w42 = (- w39 );
  /* #101: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #102: @44 = @0[9] */
  w44 = wr00[9];
  /* #103: @45 = (2.*@44) */
  w45 = (2.* w44 );
  /* #104: @46 = @0[8] */
  w46 = wr00[8];
  /* #105: @47 = (2.*@46) */
  w47 = (2.* w46 );
  /* #106: @47 = (-@47) */
  w47 = (- w47 );
  /* #107: @24 = horzcat(@42, @45, @47) */
  rr=w24;
  *rr++ = w42;
  *rr++ = w45;
  *rr++ = w47;
  /* #108: @24 = @24' */
  /* #109: @22 = horzcat(@17, @23, @24) */
  rr=w22;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #110: @6 = mac(@22,@13,@6) */
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w13+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #111: @17 = zeros(3x1) */
  casadi_clear(w17, 3);
  /* #112: @17 = mac(@22,@21,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #113: @35 = zeros(3x1,0nz) */
  /* #114: @36 = zeros(3x1,0nz) */
  /* #115: @38 = vertcat(@6, @17, @35, @36) */
  rr=w38;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  /* #116: @37 = @38[:6] */
  for (rr=w37, cs=w38+0; cs!=w38+6; cs+=1) *rr++ = *cs;
  /* #117: (@5[2:26:4] = @37) */
  for (rr=w05+2, cs=w37; rr!=w05+26; rr+=4) *rr = *cs++;
  /* #118: @6 = zeros(3x1) */
  casadi_clear(w06, 3);
  /* #119: @42 = @0[9] */
  w42 = wr00[9];
  /* #120: @45 = (2.*@42) */
  w45 = (2.* w42 );
  /* #121: @45 = (-@45) */
  w45 = (- w45 );
  /* #122: @47 = @0[6] */
  w47 = wr00[6];
  /* #123: @48 = (-@47) */
  w48 = (- w47 );
  /* #124: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #125: @49 = @0[7] */
  w49 = wr00[7];
  /* #126: @50 = (2.*@49) */
  w50 = (2.* w49 );
  /* #127: @17 = horzcat(@45, @48, @50) */
  rr=w17;
  *rr++ = w45;
  *rr++ = w48;
  *rr++ = w50;
  /* #128: @17 = @17' */
  /* #129: @45 = @0[6] */
  w45 = wr00[6];
  /* #130: @48 = (2.*@45) */
  w48 = (2.* w45 );
  /* #131: @50 = @0[9] */
  w50 = wr00[9];
  /* #132: @51 = (2.*@50) */
  w51 = (2.* w50 );
  /* #133: @51 = (-@51) */
  w51 = (- w51 );
  /* #134: @52 = @0[8] */
  w52 = wr00[8];
  /* #135: @53 = (2.*@52) */
  w53 = (2.* w52 );
  /* #136: @23 = horzcat(@48, @51, @53) */
  rr=w23;
  *rr++ = w48;
  *rr++ = w51;
  *rr++ = w53;
  /* #137: @23 = @23' */
  /* #138: @48 = @0[7] */
  w48 = wr00[7];
  /* #139: @51 = (2.*@48) */
  w51 = (2.* w48 );
  /* #140: @53 = @0[8] */
  w53 = wr00[8];
  /* #141: @54 = (2.*@53) */
  w54 = (2.* w53 );
  /* #142: @55 = @0[9] */
  w55 = wr00[9];
  /* #143: @56 = (2.*@55) */
  w56 = (2.* w55 );
  /* #144: @24 = horzcat(@51, @54, @56) */
  rr=w24;
  *rr++ = w51;
  *rr++ = w54;
  *rr++ = w56;
  /* #145: @24 = @24' */
  /* #146: @22 = horzcat(@17, @23, @24) */
  rr=w22;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #147: @6 = mac(@22,@13,@6) */
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w13+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #148: @17 = zeros(3x1) */
  casadi_clear(w17, 3);
  /* #149: @17 = mac(@22,@21,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #150: @35 = zeros(3x1,0nz) */
  /* #151: @36 = zeros(3x1,0nz) */
  /* #152: @37 = vertcat(@6, @17, @35, @36) */
  rr=w37;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  /* #153: @38 = @37[:6] */
  for (rr=w38, cs=w37+0; cs!=w37+6; cs+=1) *rr++ = *cs;
  /* #154: (@5[3:27:4] = @38) */
  for (rr=w05+3, cs=w38; rr!=w05+27; rr+=4) *rr = *cs++;
  /* #155: @3 = mac(@4,@5,@3) */
  casadi_mtimes(wr04, casadi_s3, w05, casadi_s2, w03, casadi_s1, w, 0);
  /* #156: @57 = 
  [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]] */
  wr57 = casadi_c2;
  /* #157: @58 = zeros(12x12) */
  casadi_clear(w58, 144);
  /* #158: @59 = zeros(12x10) */
  casadi_clear(w59, 120);
  /* #159: @60 = @5' */
  casadi_trans(w05,casadi_s2, w60, casadi_s4, iw);
  /* #160: @59 = mac(@60,@4,@59) */
  casadi_mtimes(w60, casadi_s4, wr04, casadi_s3, w59, casadi_s5, w, 0);
  /* #161: @58 = mac(@59,@5,@58) */
  casadi_mtimes(w59, casadi_s5, w05, casadi_s2, w58, casadi_s6, w, 0);
  /* #162: @51 = input[3][0] */
  w51 = arg[3] ? arg[3][0] : 0;
  /* #163: @6 = @51[0, 0, 0] */
  for (cii=casadi_s7, rr=w06, cs=(&w51); cii!=casadi_s7+3; ++cii) *rr++ = cs[*cii];
  /* #164: @61 = zeros(3x9) */
  casadi_clear(w61, 27);
  /* #165: @5 = horzcat(@6, @61) */
  rr=w05;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w61; i<27; ++i) *rr++ = *cs++;
  /* #166: @62 = @5' */
  casadi_trans(w05,casadi_s9, w62, casadi_s8, iw);
  /* #167: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #168: @51 = input[5][0] */
  w51 = arg[5] ? arg[5][0] : 0;
  /* #169: @6 = @51[0, 0, 0] */
  for (cii=casadi_s7, rr=w06, cs=(&w51); cii!=casadi_s7+3; ++cii) *rr++ = cs[*cii];
  /* #170: @63 = zeros(3x6) */
  casadi_clear(w63, 18);
  /* #171: @5 = horzcat(@22, @6, @63) */
  rr=w05;
  for (i=0, cs=w22; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w63; i<18; ++i) *rr++ = *cs++;
  /* #172: @64 = @5' */
  casadi_trans(w05,casadi_s11, w64, casadi_s10, iw);
  /* #173: @63 = zeros(3x6) */
  casadi_clear(w63, 18);
  /* #174: @51 = input[8][0] */
  w51 = arg[8] ? arg[8][0] : 0;
  /* #175: @6 = @51[0, 0, 0] */
  for (cii=casadi_s7, rr=w06, cs=(&w51); cii!=casadi_s7+3; ++cii) *rr++ = cs[*cii];
  /* #176: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #177: @5 = horzcat(@63, @6, @22) */
  rr=w05;
  for (i=0, cs=w63; i<18; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<9; ++i) *rr++ = *cs++;
  /* #178: @65 = @5' */
  casadi_trans(w05,casadi_s13, w65, casadi_s12, iw);
  /* #179: @61 = zeros(3x9) */
  casadi_clear(w61, 27);
  /* #180: @51 = input[9][0] */
  w51 = arg[9] ? arg[9][0] : 0;
  /* #181: @6 = @51[0, 0, 0] */
  for (cii=casadi_s7, rr=w06, cs=(&w51); cii!=casadi_s7+3; ++cii) *rr++ = cs[*cii];
  /* #182: @5 = horzcat(@61, @6) */
  rr=w05;
  for (i=0, cs=w61; i<27; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  /* #183: @66 = @5' */
  casadi_trans(w05,casadi_s15, w66, casadi_s14, iw);
  /* #184: @59 = horzcat(@62, @64, @65, @66) */
  rr=w59;
  for (i=0, cs=w62; i<30; ++i) *rr++ = *cs++;
  for (i=0, cs=w64; i<30; ++i) *rr++ = *cs++;
  for (i=0, cs=w65; i<30; ++i) *rr++ = *cs++;
  for (i=0, cs=w66; i<30; ++i) *rr++ = *cs++;
  /* #185: @67 = @59' */
  casadi_trans(w59,casadi_s16, w67, casadi_s16, iw);
  /* #186: @68 = dense(@67) */
  casadi_densify(w67, casadi_s16, w68, 0);
  /* #187: @58 = (@58+@68) */
  for (i=0, rr=w58, cs=w68; i<144; ++i) (*rr++) += (*cs++);
  /* #188: @57 = (@58\@57) */
  rr = w57;
  ss = w58;
  casadi_copy(wr57, 144, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[78], r[78], beta[12], w[24];
    casadi_qr(casadi_s6, ss, w, casadi_s18, v, casadi_s19, r, beta, casadi_s17, casadi_s17);
    casadi_qr_solve(rr, 12, 0, casadi_s18, v, casadi_s19, r, beta, casadi_s17, casadi_s17, w);
  }
  /* #189: @2 = mac(@3,@57,@2) */
  for (i=0, rr=w02; i<12; ++i) for (j=0; j<10; ++j, ++rr) for (k=0, cs=w03+j, ct=w57+i*12; k<12; ++k) *rr += cs[k*10]**ct++;
  /* #190: @6 = input[2][0] */
  casadi_copy(arg[2], 3, w06);
  /* #191: @17 = input[4][0] */
  casadi_copy(arg[4], 3, w17);
  /* #192: @23 = input[6][0] */
  casadi_copy(arg[6], 3, w23);
  /* #193: @24 = input[7][0] */
  casadi_copy(arg[7], 3, w24);
  /* #194: @25 = vertcat(@6, @17, @23, @24) */
  rr=w25;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #195: @6 = zeros(3x1) */
  casadi_clear(w06, 3);
  /* #196: @7 = sq(@7) */
  w07 = casadi_sq( w07 );
  /* #197: @14 = sq(@14) */
  w14 = casadi_sq( w14 );
  /* #198: @7 = (@7+@14) */
  w07 += w14;
  /* #199: @29 = sq(@29) */
  w29 = casadi_sq( w29 );
  /* #200: @7 = (@7-@29) */
  w07 -= w29;
  /* #201: @42 = sq(@42) */
  w42 = casadi_sq( w42 );
  /* #202: @7 = (@7-@42) */
  w07 -= w42;
  /* #203: @34 = (@34*@20) */
  w34 *= w20;
  /* #204: @47 = (@47*@9) */
  w47 *= w09;
  /* #205: @34 = (@34-@47) */
  w34 -= w47;
  /* #206: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #207: @49 = (@49*@27) */
  w49 *= w27;
  /* #208: @40 = (@40*@11) */
  w40 *= w11;
  /* #209: @49 = (@49+@40) */
  w49 += w40;
  /* #210: @49 = (2.*@49) */
  w49 = (2.* w49 );
  /* #211: @17 = horzcat(@7, @34, @49) */
  rr=w17;
  *rr++ = w07;
  *rr++ = w34;
  *rr++ = w49;
  /* #212: @17 = @17' */
  /* #213: @32 = (@32*@18) */
  w32 *= w18;
  /* #214: @45 = (@45*@8) */
  w45 *= w08;
  /* #215: @32 = (@32+@45) */
  w32 += w45;
  /* #216: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #217: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #218: @28 = sq(@28) */
  w28 = casadi_sq( w28 );
  /* #219: @12 = (@12-@28) */
  w12 -= w28;
  /* #220: @41 = sq(@41) */
  w41 = casadi_sq( w41 );
  /* #221: @12 = (@12+@41) */
  w12 += w41;
  /* #222: @50 = sq(@50) */
  w50 = casadi_sq( w50 );
  /* #223: @12 = (@12-@50) */
  w12 -= w50;
  /* #224: @52 = (@52*@43) */
  w52 *= w43;
  /* #225: @30 = (@30*@15) */
  w30 *= w15;
  /* #226: @52 = (@52-@30) */
  w52 -= w30;
  /* #227: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #228: @23 = horzcat(@32, @12, @52) */
  rr=w23;
  *rr++ = w32;
  *rr++ = w12;
  *rr++ = w52;
  /* #229: @23 = @23' */
  /* #230: @48 = (@48*@26) */
  w48 *= w26;
  /* #231: @39 = (@39*@10) */
  w39 *= w10;
  /* #232: @48 = (@48-@39) */
  w48 -= w39;
  /* #233: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #234: @31 = (@31*@16) */
  w31 *= w16;
  /* #235: @53 = (@53*@44) */
  w53 *= w44;
  /* #236: @31 = (@31+@53) */
  w31 += w53;
  /* #237: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #238: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #239: @33 = sq(@33) */
  w33 = casadi_sq( w33 );
  /* #240: @19 = (@19-@33) */
  w19 -= w33;
  /* #241: @46 = sq(@46) */
  w46 = casadi_sq( w46 );
  /* #242: @19 = (@19-@46) */
  w19 -= w46;
  /* #243: @55 = sq(@55) */
  w55 = casadi_sq( w55 );
  /* #244: @19 = (@19+@55) */
  w19 += w55;
  /* #245: @24 = horzcat(@48, @31, @19) */
  rr=w24;
  *rr++ = w48;
  *rr++ = w31;
  *rr++ = w19;
  /* #246: @24 = @24' */
  /* #247: @22 = horzcat(@17, @23, @24) */
  rr=w22;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #248: @6 = mac(@22,@13,@6) */
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w13+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #249: @13 = zeros(3x1) */
  casadi_clear(w13, 3);
  /* #250: @13 = mac(@22,@21,@13) */
  for (i=0, rr=w13; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #251: @21 = @0[:3] */
  wr21 = wr00+0;
  /* #252: @17 = @0[3:6] */
  wr17 = wr00+3;
  /* #253: @69 = vertcat(@6, @13, @21, @17) */
  rr=w69;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr17; i<3; ++i) *rr++ = *cs++;
  /* #254: @25 = (@25-@69) */
  for (i=0, rr=w25, cs=w69; i<12; ++i) (*rr++) -= (*cs++);
  /* #255: @1 = mac(@2,@25,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<10; ++j, ++rr) for (k=0, cs=w02+j, ct=w25+i*12; k<12; ++k) *rr += cs[k*10]**ct++;
  /* #256: @0 = (@0+@1) */
  for (i=0, rr=w00, cr=wr00, cs=w01; i<10; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #257: output[0][0] = @0 */
  casadi_copy(w00, 10, res[0]);
  /* #258: @70 = zeros(10x10) */
  casadi_clear(w70, 100);
  /* #259: @71 = zeros(10x10) */
  casadi_clear(w71, 100);
  /* #260: @71 = mac(@2,@60,@71) */
  casadi_mtimes(w02, casadi_s1, w60, casadi_s4, w71, casadi_s3, w, 0);
  /* #261: @70 = mac(@71,@4,@70) */
  for (i=0, rr=w70; i<10; ++i) for (j=0; j<10; ++j, ++rr) for (k=0, cs=w71+j, ct=wr04+i*10; k<10; ++k) *rr += cs[k*10]**ct++;
  /* #262: @4 = (@4-@70) */
  for (i=0, rr=w04, cr=wr04, cs=w70; i<100; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #263: output[1][0] = @4 */
  casadi_copy(w04, 100, res[1]);
  /* #264: output[2][0] = @25 */
  casadi_copy(w25, 12, res[2]);
  /* #265: output[3][0] = @2 */
  casadi_copy(w02, 120, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int ekf_correct(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ekf_correct_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ekf_correct_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ekf_correct_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ekf_correct_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ekf_correct_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ekf_correct_incref(void) {
}

CASADI_SYMBOL_EXPORT void ekf_correct_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ekf_correct_n_in(void) { return 10;}

CASADI_SYMBOL_EXPORT casadi_int ekf_correct_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real ekf_correct_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ekf_correct_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    case 9: return "i9";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ekf_correct_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ekf_correct_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s20;
    case 1: return casadi_s21;
    case 2: return casadi_s22;
    case 3: return casadi_s23;
    case 4: return casadi_s22;
    case 5: return casadi_s23;
    case 6: return casadi_s22;
    case 7: return casadi_s22;
    case 8: return casadi_s23;
    case 9: return casadi_s23;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ekf_correct_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s20;
    case 1: return casadi_s21;
    case 2: return casadi_s24;
    case 3: return casadi_s25;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ekf_correct_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 13;
  if (sz_w) *sz_w = 1571;
  return 0;
}

CASADI_SYMBOL_EXPORT int ekf_correct_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 13*sizeof(casadi_int);
  if (sz_w) *sz_w = 1571*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
