/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ekf_predict_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real float
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s2[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[10] = 
  {0, 2, 4, 7, 12, 17, 21, 25,
  29, 33};
static const casadi_int casadi_s4[6] = {1, 3, 5, 6, 11, 16};
static const casadi_int casadi_s5[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s6[7] = {8, 13, 18, 22, 26, 30, 34};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s8[7] = {9, 14, 19, 23, 27, 31, 35};
static const casadi_int casadi_s9[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s10[7] = {10, 15, 20, 24, 28, 32, 36};
static const casadi_int casadi_s11[50] = 
  {10, 10, 0, 1, 2, 3, 5, 7,
  9, 16, 23, 30, 37, 0, 1, 2,
  0, 3, 1, 4, 2, 5, 3, 4,
  5, 6, 7, 8, 9, 3, 4, 5,
  6, 7, 8, 9, 3, 4, 5, 6,
  7, 8, 9, 3, 4, 5, 6, 7,
  8, 9};
static const casadi_int casadi_s12[50] = 
  {10, 10, 0, 2, 4, 6, 11, 16,
  21, 25, 29, 33, 37, 0, 3, 1,
  4, 2, 5, 3, 6, 7, 8, 9,
  4, 6, 7, 8, 9, 5, 6, 7,
  8, 9, 6, 7, 8, 9, 6, 7,
  8, 9, 6, 7, 8, 9, 6, 7,
  8, 9};
static const casadi_int casadi_s13[113] = 
  {10, 10, 0, 10, 20, 30, 40, 50,
  60, 70, 80, 90, 100, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9};
static const casadi_int casadi_s14[3] = {0, 0, 0};
static const casadi_int casadi_s15[30] = 
  {10, 3, 0, 8, 16, 24, 0, 3,
  4, 5, 6, 7, 8, 9, 1, 3,
  4, 5, 6, 7, 8, 9, 2, 3,
  4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s16[37] = 
  {3, 10, 0, 1, 2, 3, 6, 9,
  12, 15, 18, 21, 24, 0, 1, 2,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2};
static const casadi_int casadi_s17[30] = 
  {10, 3, 0, 8, 16, 24, 0, 1,
  2, 3, 6, 7, 8, 9, 0, 1,
  2, 4, 6, 7, 8, 9, 0, 1,
  2, 5, 6, 7, 8, 9};
static const casadi_int casadi_s18[37] = 
  {3, 10, 0, 3, 6, 9, 10, 11,
  12, 15, 18, 21, 24, 0, 1, 2,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2};
static const casadi_int casadi_s19[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s20[101] = 
  {10, 10, 0, 8, 16, 24, 32, 40,
  48, 58, 68, 78, 88, 0, 3, 4,
  5, 6, 7, 8, 9, 1, 3, 4,
  5, 6, 7, 8, 9, 2, 3, 4,
  5, 6, 7, 8, 9, 0, 1, 2,
  3, 6, 7, 8, 9, 0, 1, 2,
  4, 6, 7, 8, 9, 0, 1, 2,
  5, 6, 7, 8, 9, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9};
static const casadi_int casadi_s21[3] = {1, 1, 1};
static const casadi_int casadi_s22[3] = {3, 1, 1};
static const casadi_int casadi_s23[3] = {10, 10, 1};
static const casadi_int casadi_s24[3] = {4, 1, 1};
static const casadi_int casadi_s25[3] = {10, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[16] = 
  {1., 0., 0., 0., 0., 1., 0., 0.,
  0., 0., 1., 0., 0., 0., 0., 1.};

static const casadi_real casadi_zeros[100] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* ekf_predict:(i0,i1[3],i2[3],i3,i4,i5[10x10],i6[4],i7[3],i8[3])->(o0[10],o1[10x10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+10, *w01=w+13, w02, *w03=w+17, *w04=w+20, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+52, w34;
  casadi_real w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, *w46=w+67;
  casadi_real *w47=w+70, *w48=w+79, *w49=w+83, *w50=w+99, *w51=w+103, *w52=w+112, *w53=w+124, *w54=w+136, *w55=w+152, *w56=w+168, *w57=w+268, *w58=w+368;
  casadi_real *w59=w+405, *w60=w+408, *w62=w+418, *w63=w+424, *w64=w+430, *w65=w+437, *w66=w+444, *w68=w+581, *w69=w+605, *w70=w+629, *w71=w+653, *w72=w+662;
  casadi_real *w73=w+674, *w74=w+686, *w75=w+726, *w76=w+766, *w77=w+854;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr49, *wr67;
  /* #0: @0 = input[7][0] */
  casadi_copy(arg[7], 3, w00);
  /* #1: @1 = input[8][0] */
  casadi_copy(arg[8], 3, w01);
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = (@1*@2) */
  for (i=0, rr=w03, cr=w01; i<3; ++i) (*rr++)  = ((*cr++)*w02);
  /* #4: @0 = (@0+@3) */
  for (i=0, rr=w00, cs=w03; i<3; ++i) (*rr++) += (*cs++);
  /* #5: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #6: @0 = zeros(3x1) */
  casadi_clear(w00, 3);
  /* #7: @4 = input[6][0] */
  casadi_copy(arg[6], 4, w04);
  /* #8: @5 = @4[0] */
  for (rr=(&w05), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #9: @6 = sq(@5) */
  w06 = casadi_sq( w05 );
  /* #10: @7 = @4[1] */
  for (rr=(&w07), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #11: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #12: @6 = (@6+@8) */
  w06 += w08;
  /* #13: @8 = @4[2] */
  for (rr=(&w08), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #14: @9 = sq(@8) */
  w09 = casadi_sq( w08 );
  /* #15: @6 = (@6-@9) */
  w06 -= w09;
  /* #16: @9 = @4[3] */
  for (rr=(&w09), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #17: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #18: @6 = (@6-@10) */
  w06 -= w10;
  /* #19: @10 = @4[1] */
  for (rr=(&w10), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #20: @11 = @4[2] */
  for (rr=(&w11), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #21: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #22: @13 = @4[0] */
  for (rr=(&w13), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #23: @14 = @4[3] */
  for (rr=(&w14), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #24: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #25: @12 = (@12-@15) */
  w12 -= w15;
  /* #26: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #27: @15 = @4[1] */
  for (rr=(&w15), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #28: @16 = @4[3] */
  for (rr=(&w16), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #29: @17 = (@15*@16) */
  w17  = (w15*w16);
  /* #30: @18 = @4[0] */
  for (rr=(&w18), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #31: @19 = @4[2] */
  for (rr=(&w19), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #32: @20 = (@18*@19) */
  w20  = (w18*w19);
  /* #33: @17 = (@17+@20) */
  w17 += w20;
  /* #34: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #35: @3 = horzcat(@6, @12, @17) */
  rr=w03;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w17;
  /* #36: @3 = @3' */
  /* #37: @6 = @4[1] */
  for (rr=(&w06), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #38: @12 = @4[2] */
  for (rr=(&w12), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #39: @17 = (@6*@12) */
  w17  = (w06*w12);
  /* #40: @20 = @4[0] */
  for (rr=(&w20), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #41: @21 = @4[3] */
  for (rr=(&w21), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #42: @22 = (@20*@21) */
  w22  = (w20*w21);
  /* #43: @17 = (@17+@22) */
  w17 += w22;
  /* #44: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #45: @22 = @4[0] */
  for (rr=(&w22), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #46: @23 = sq(@22) */
  w23 = casadi_sq( w22 );
  /* #47: @24 = @4[1] */
  for (rr=(&w24), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #48: @25 = sq(@24) */
  w25 = casadi_sq( w24 );
  /* #49: @23 = (@23-@25) */
  w23 -= w25;
  /* #50: @25 = @4[2] */
  for (rr=(&w25), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #51: @26 = sq(@25) */
  w26 = casadi_sq( w25 );
  /* #52: @23 = (@23+@26) */
  w23 += w26;
  /* #53: @26 = @4[3] */
  for (rr=(&w26), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #54: @27 = sq(@26) */
  w27 = casadi_sq( w26 );
  /* #55: @23 = (@23-@27) */
  w23 -= w27;
  /* #56: @27 = @4[2] */
  for (rr=(&w27), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #57: @28 = @4[3] */
  for (rr=(&w28), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #58: @29 = (@27*@28) */
  w29  = (w27*w28);
  /* #59: @30 = @4[0] */
  for (rr=(&w30), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #60: @31 = @4[1] */
  for (rr=(&w31), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #61: @32 = (@30*@31) */
  w32  = (w30*w31);
  /* #62: @29 = (@29-@32) */
  w29 -= w32;
  /* #63: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #64: @33 = horzcat(@17, @23, @29) */
  rr=w33;
  *rr++ = w17;
  *rr++ = w23;
  *rr++ = w29;
  /* #65: @33 = @33' */
  /* #66: @17 = @4[1] */
  for (rr=(&w17), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #67: @23 = @4[3] */
  for (rr=(&w23), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #68: @29 = (@17*@23) */
  w29  = (w17*w23);
  /* #69: @32 = @4[0] */
  for (rr=(&w32), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #70: @34 = @4[2] */
  for (rr=(&w34), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #71: @35 = (@32*@34) */
  w35  = (w32*w34);
  /* #72: @29 = (@29-@35) */
  w29 -= w35;
  /* #73: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #74: @35 = @4[0] */
  for (rr=(&w35), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #75: @36 = @4[1] */
  for (rr=(&w36), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #76: @37 = (@35*@36) */
  w37  = (w35*w36);
  /* #77: @38 = @4[2] */
  for (rr=(&w38), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #78: @39 = @4[3] */
  for (rr=(&w39), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #79: @40 = (@38*@39) */
  w40  = (w38*w39);
  /* #80: @37 = (@37+@40) */
  w37 += w40;
  /* #81: @37 = (2.*@37) */
  w37 = (2.* w37 );
  /* #82: @40 = @4[0] */
  for (rr=(&w40), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #83: @41 = sq(@40) */
  w41 = casadi_sq( w40 );
  /* #84: @42 = @4[1] */
  for (rr=(&w42), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #85: @43 = sq(@42) */
  w43 = casadi_sq( w42 );
  /* #86: @41 = (@41-@43) */
  w41 -= w43;
  /* #87: @43 = @4[2] */
  for (rr=(&w43), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #88: @44 = sq(@43) */
  w44 = casadi_sq( w43 );
  /* #89: @41 = (@41-@44) */
  w41 -= w44;
  /* #90: @44 = @4[3] */
  for (rr=(&w44), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #91: @45 = sq(@44) */
  w45 = casadi_sq( w44 );
  /* #92: @41 = (@41+@45) */
  w41 += w45;
  /* #93: @46 = horzcat(@29, @37, @41) */
  rr=w46;
  *rr++ = w29;
  *rr++ = w37;
  *rr++ = w41;
  /* #94: @46 = @46' */
  /* #95: @47 = horzcat(@3, @33, @46) */
  rr=w47;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  /* #96: @3 = input[2][0] */
  casadi_copy(arg[2], 3, w03);
  /* #97: @0 = mac(@47,@3,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w47+j, ct=w03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #98: @33 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w33);
  /* #99: @0 = (@0-@33) */
  for (i=0, rr=w00, cs=w33; i<3; ++i) (*rr++) -= (*cs++);
  /* #100: @0 = (@0*@2) */
  for (i=0, rr=w00; i<3; ++i) (*rr++) *= w02;
  /* #101: @1 = (@1+@0) */
  for (i=0, rr=w01, cs=w00; i<3; ++i) (*rr++) += (*cs++);
  /* #102: output[0][1] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+3);
  /* #103: @48 = zeros(4x1) */
  casadi_clear(w48, 4);
  /* #104: @49 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  wr49 = casadi_c1;
  /* #105: @29 = 2 */
  w29 = 2.;
  /* #106: @29 = (@2/@29) */
  w29  = (w02/w29);
  /* #107: @37 = 0 */
  w37 = 0.;
  /* #108: @1 = input[1][0] */
  casadi_copy(arg[1], 3, w01);
  /* #109: @0 = @1' */
  casadi_copy(w01, 3, w00);
  /* #110: @0 = (-@0) */
  for (i=0, rr=w00, cs=w00; i<3; ++i) *rr++ = (- *cs++ );
  /* #111: @50 = horzcat(@37, @0) */
  rr=w50;
  *rr++ = w37;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  /* #112: @50 = @50' */
  /* #113: @37 = 0 */
  w37 = 0.;
  /* #114: @41 = @1[2] */
  for (rr=(&w41), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #115: @41 = (-@41) */
  w41 = (- w41 );
  /* #116: @45 = @1[1] */
  for (rr=(&w45), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #117: @0 = horzcat(@37, @41, @45) */
  rr=w00;
  *rr++ = w37;
  *rr++ = w41;
  *rr++ = w45;
  /* #118: @0 = @0' */
  /* #119: @37 = @1[2] */
  for (rr=(&w37), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #120: @41 = 0 */
  w41 = 0.;
  /* #121: @45 = @1[0] */
  for (rr=(&w45), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #122: @45 = (-@45) */
  w45 = (- w45 );
  /* #123: @33 = horzcat(@37, @41, @45) */
  rr=w33;
  *rr++ = w37;
  *rr++ = w41;
  *rr++ = w45;
  /* #124: @33 = @33' */
  /* #125: @37 = @1[1] */
  for (rr=(&w37), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #126: @37 = (-@37) */
  w37 = (- w37 );
  /* #127: @41 = @1[0] */
  for (rr=(&w41), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #128: @45 = 0 */
  w45 = 0.;
  /* #129: @46 = horzcat(@37, @41, @45) */
  rr=w46;
  *rr++ = w37;
  *rr++ = w41;
  *rr++ = w45;
  /* #130: @46 = @46' */
  /* #131: @47 = horzcat(@0, @33, @46) */
  rr=w47;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  /* #132: @51 = @47' */
  for (i=0, rr=w51, cs=w47; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #133: @51 = (-@51) */
  for (i=0, rr=w51, cs=w51; i<9; ++i) *rr++ = (- *cs++ );
  /* #134: @52 = horzcat(@1, @51) */
  rr=w52;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w51; i<9; ++i) *rr++ = *cs++;
  /* #135: @53 = @52' */
  for (i=0, rr=w53, cs=w52; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #136: @54 = horzcat(@50, @53) */
  rr=w54;
  for (i=0, cs=w50; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<12; ++i) *rr++ = *cs++;
  /* #137: @55 = @54' */
  for (i=0, rr=w55, cs=w54; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #138: @55 = (@29*@55) */
  for (i=0, rr=w55, cs=w55; i<16; ++i) (*rr++)  = (w29*(*cs++));
  /* #139: @49 = (@49+@55) */
  for (i=0, rr=w49, cr=wr49, cs=w55; i<16; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #140: @48 = mac(@49,@4,@48) */
  for (i=0, rr=w48; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w49+j, ct=w04+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #141: output[0][2] = @48 */
  if (res[0]) casadi_copy(w48, 4, res[0]+6);
  /* #142: @56 = zeros(10x10) */
  casadi_clear(w56, 100);
  /* #143: @57 = zeros(10x10) */
  casadi_clear(w57, 100);
  /* #144: @58 = zeros(10x10,37nz) */
  casadi_clear(w58, 37);
  /* #145: @48 = ones(10x1,4nz) */
  casadi_fill(w48, 4, 1.);
  /* #146: {@1, NULL, @29} = vertsplit(@48) */
  casadi_copy(w48, 3, w01);
  w29 = w48[3];
  /* #147: @0 = zeros(3x1) */
  casadi_clear(w00, 3);
  /* #148: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #149: @37 = @29[0] */
  for (rr=(&w37), cs=(&w29)+0; cs!=(&w29)+1; cs+=1) *rr++ = *cs;
  /* #150: @5 = (@5*@37) */
  w05 *= w37;
  /* #151: @37 = @29[0] */
  for (rr=(&w37), cs=(&w29)+0; cs!=(&w29)+1; cs+=1) *rr++ = *cs;
  /* #152: @14 = (@14*@37) */
  w14 *= w37;
  /* #153: @14 = (-@14) */
  w14 = (- w14 );
  /* #154: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #155: @37 = @29[0] */
  for (rr=(&w37), cs=(&w29)+0; cs!=(&w29)+1; cs+=1) *rr++ = *cs;
  /* #156: @19 = (@19*@37) */
  w19 *= w37;
  /* #157: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #158: @33 = horzcat(@5, @14, @19) */
  rr=w33;
  *rr++ = w05;
  *rr++ = w14;
  *rr++ = w19;
  /* #159: @33 = @33' */
  /* #160: @5 = @29[0] */
  for (rr=(&w05), cs=(&w29)+0; cs!=(&w29)+1; cs+=1) *rr++ = *cs;
  /* #161: @21 = (@21*@5) */
  w21 *= w05;
  /* #162: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #163: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #164: @5 = @29[0] */
  for (rr=(&w05), cs=(&w29)+0; cs!=(&w29)+1; cs+=1) *rr++ = *cs;
  /* #165: @22 = (@22*@5) */
  w22 *= w05;
  /* #166: @5 = @29[0] */
  for (rr=(&w05), cs=(&w29)+0; cs!=(&w29)+1; cs+=1) *rr++ = *cs;
  /* #167: @31 = (@31*@5) */
  w31 *= w05;
  /* #168: @31 = (-@31) */
  w31 = (- w31 );
  /* #169: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #170: @46 = horzcat(@21, @22, @31) */
  rr=w46;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w31;
  /* #171: @46 = @46' */
  /* #172: @21 = @29[0] */
  for (rr=(&w21), cs=(&w29)+0; cs!=(&w29)+1; cs+=1) *rr++ = *cs;
  /* #173: @34 = (@34*@21) */
  w34 *= w21;
  /* #174: @34 = (-@34) */
  w34 = (- w34 );
  /* #175: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #176: @21 = @29[0] */
  for (rr=(&w21), cs=(&w29)+0; cs!=(&w29)+1; cs+=1) *rr++ = *cs;
  /* #177: @36 = (@36*@21) */
  w36 *= w21;
  /* #178: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #179: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #180: @21 = @29[0] */
  for (rr=(&w21), cs=(&w29)+0; cs!=(&w29)+1; cs+=1) *rr++ = *cs;
  /* #181: @40 = (@40*@21) */
  w40 *= w21;
  /* #182: @59 = horzcat(@34, @36, @40) */
  rr=w59;
  *rr++ = w34;
  *rr++ = w36;
  *rr++ = w40;
  /* #183: @59 = @59' */
  /* #184: @51 = horzcat(@33, @46, @59) */
  rr=w51;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<3; ++i) *rr++ = *cs++;
  /* #185: @0 = mac(@51,@3,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w51+j, ct=w03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #186: @0 = (@2*@0) */
  for (i=0, rr=w00, cs=w00; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #187: @48 = zeros(4x1) */
  casadi_clear(w48, 4);
  /* #188: @48 = mac(@49,@29,@48) */
  casadi_mtimes(w49, casadi_s2, (&w29), casadi_s1, w48, casadi_s0, w, 0);
  /* #189: @60 = vertcat(@1, @0, @48) */
  rr=w60;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<4; ++i) *rr++ = *cs++;
  /* #190: (@58[0, 2, 4, 7, 12, 17, 21, 25, 29, 33] = @60) */
  for (cii=casadi_s3, rr=w58, cs=w60; cii!=casadi_s3+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #191: @1 = ones(10x1,3nz) */
  casadi_fill(w01, 3, 1.);
  /* #192: {NULL, @0, NULL} = vertsplit(@1) */
  casadi_copy(w01, 3, w00);
  /* #193: @1 = (@2*@0) */
  for (i=0, rr=w01, cs=w00; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #194: @61 = zeros(4x1,0nz) */
  /* #195: @62 = vertcat(@1, @0, @61) */
  rr=w62;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  /* #196: @63 = @62[:6] */
  for (rr=w63, cs=w62+0; cs!=w62+6; cs+=1) *rr++ = *cs;
  /* #197: (@58[1, 3, 5, 6, 11, 16] = @63) */
  for (cii=casadi_s4, rr=w58, cs=w63; cii!=casadi_s4+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #198: @61 = zeros(3x1,0nz) */
  /* #199: @1 = zeros(3x1) */
  casadi_clear(w01, 3);
  /* #200: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #201: @29 = ones(10x1,1nz) */
  w29 = 1.;
  /* #202: {NULL, NULL, @34} = vertsplit(@29) */
  w34 = w29;
  /* #203: @29 = @34[0] */
  for (rr=(&w29), cs=(&w34)+0; cs!=(&w34)+1; cs+=1) *rr++ = *cs;
  /* #204: @7 = (@7*@29) */
  w07 *= w29;
  /* #205: @29 = @34[0] */
  for (rr=(&w29), cs=(&w34)+0; cs!=(&w34)+1; cs+=1) *rr++ = *cs;
  /* #206: @11 = (@11*@29) */
  w11 *= w29;
  /* #207: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #208: @29 = @34[0] */
  for (rr=(&w29), cs=(&w34)+0; cs!=(&w34)+1; cs+=1) *rr++ = *cs;
  /* #209: @16 = (@16*@29) */
  w16 *= w29;
  /* #210: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #211: @0 = horzcat(@7, @11, @16) */
  rr=w00;
  *rr++ = w07;
  *rr++ = w11;
  *rr++ = w16;
  /* #212: @0 = @0' */
  /* #213: @7 = @34[0] */
  for (rr=(&w07), cs=(&w34)+0; cs!=(&w34)+1; cs+=1) *rr++ = *cs;
  /* #214: @12 = (@12*@7) */
  w12 *= w07;
  /* #215: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #216: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #217: @7 = @34[0] */
  for (rr=(&w07), cs=(&w34)+0; cs!=(&w34)+1; cs+=1) *rr++ = *cs;
  /* #218: @24 = (@24*@7) */
  w24 *= w07;
  /* #219: @24 = (-@24) */
  w24 = (- w24 );
  /* #220: @7 = @34[0] */
  for (rr=(&w07), cs=(&w34)+0; cs!=(&w34)+1; cs+=1) *rr++ = *cs;
  /* #221: @30 = (@30*@7) */
  w30 *= w07;
  /* #222: @30 = (-@30) */
  w30 = (- w30 );
  /* #223: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #224: @33 = horzcat(@12, @24, @30) */
  rr=w33;
  *rr++ = w12;
  *rr++ = w24;
  *rr++ = w30;
  /* #225: @33 = @33' */
  /* #226: @12 = @34[0] */
  for (rr=(&w12), cs=(&w34)+0; cs!=(&w34)+1; cs+=1) *rr++ = *cs;
  /* #227: @23 = (@23*@12) */
  w23 *= w12;
  /* #228: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #229: @12 = @34[0] */
  for (rr=(&w12), cs=(&w34)+0; cs!=(&w34)+1; cs+=1) *rr++ = *cs;
  /* #230: @35 = (@35*@12) */
  w35 *= w12;
  /* #231: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #232: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #233: @12 = @34[0] */
  for (rr=(&w12), cs=(&w34)+0; cs!=(&w34)+1; cs+=1) *rr++ = *cs;
  /* #234: @42 = (@42*@12) */
  w42 *= w12;
  /* #235: @42 = (-@42) */
  w42 = (- w42 );
  /* #236: @46 = horzcat(@23, @35, @42) */
  rr=w46;
  *rr++ = w23;
  *rr++ = w35;
  *rr++ = w42;
  /* #237: @46 = @46' */
  /* #238: @51 = horzcat(@0, @33, @46) */
  rr=w51;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  /* #239: @1 = mac(@51,@3,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w51+j, ct=w03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #240: @1 = (@2*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #241: @48 = zeros(4x1) */
  casadi_clear(w48, 4);
  /* #242: @48 = mac(@49,@34,@48) */
  casadi_mtimes(w49, casadi_s2, (&w34), casadi_s5, w48, casadi_s0, w, 0);
  /* #243: @64 = vertcat(@61, @1, @48) */
  rr=w64;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<4; ++i) *rr++ = *cs++;
  /* #244: @65 = @64[:7] */
  for (rr=w65, cs=w64+0; cs!=w64+7; cs+=1) *rr++ = *cs;
  /* #245: (@58[8, 13, 18, 22, 26, 30, 34] = @65) */
  for (cii=casadi_s6, rr=w58, cs=w65; cii!=casadi_s6+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #246: @61 = zeros(3x1,0nz) */
  /* #247: @1 = zeros(3x1) */
  casadi_clear(w01, 3);
  /* #248: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #249: @34 = ones(10x1,1nz) */
  w34 = 1.;
  /* #250: {NULL, NULL, @23} = vertsplit(@34) */
  w23 = w34;
  /* #251: @34 = @23[0] */
  for (rr=(&w34), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #252: @8 = (@8*@34) */
  w08 *= w34;
  /* #253: @8 = (-@8) */
  w08 = (- w08 );
  /* #254: @34 = @23[0] */
  for (rr=(&w34), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #255: @10 = (@10*@34) */
  w10 *= w34;
  /* #256: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #257: @34 = @23[0] */
  for (rr=(&w34), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #258: @18 = (@18*@34) */
  w18 *= w34;
  /* #259: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #260: @0 = horzcat(@8, @10, @18) */
  rr=w00;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w18;
  /* #261: @0 = @0' */
  /* #262: @8 = @23[0] */
  for (rr=(&w08), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #263: @6 = (@6*@8) */
  w06 *= w08;
  /* #264: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #265: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #266: @8 = @23[0] */
  for (rr=(&w08), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #267: @25 = (@25*@8) */
  w25 *= w08;
  /* #268: @8 = @23[0] */
  for (rr=(&w08), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #269: @28 = (@28*@8) */
  w28 *= w08;
  /* #270: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #271: @33 = horzcat(@6, @25, @28) */
  rr=w33;
  *rr++ = w06;
  *rr++ = w25;
  *rr++ = w28;
  /* #272: @33 = @33' */
  /* #273: @6 = @23[0] */
  for (rr=(&w06), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #274: @32 = (@32*@6) */
  w32 *= w06;
  /* #275: @32 = (-@32) */
  w32 = (- w32 );
  /* #276: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #277: @6 = @23[0] */
  for (rr=(&w06), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #278: @39 = (@39*@6) */
  w39 *= w06;
  /* #279: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #280: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #281: @6 = @23[0] */
  for (rr=(&w06), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #282: @43 = (@43*@6) */
  w43 *= w06;
  /* #283: @43 = (-@43) */
  w43 = (- w43 );
  /* #284: @46 = horzcat(@32, @39, @43) */
  rr=w46;
  *rr++ = w32;
  *rr++ = w39;
  *rr++ = w43;
  /* #285: @46 = @46' */
  /* #286: @51 = horzcat(@0, @33, @46) */
  rr=w51;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  /* #287: @1 = mac(@51,@3,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w51+j, ct=w03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #288: @1 = (@2*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #289: @48 = zeros(4x1) */
  casadi_clear(w48, 4);
  /* #290: @48 = mac(@49,@23,@48) */
  casadi_mtimes(w49, casadi_s2, (&w23), casadi_s7, w48, casadi_s0, w, 0);
  /* #291: @65 = vertcat(@61, @1, @48) */
  rr=w65;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<4; ++i) *rr++ = *cs++;
  /* #292: @64 = @65[:7] */
  for (rr=w64, cs=w65+0; cs!=w65+7; cs+=1) *rr++ = *cs;
  /* #293: (@58[9, 14, 19, 23, 27, 31, 35] = @64) */
  for (cii=casadi_s8, rr=w58, cs=w64; cii!=casadi_s8+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #294: @61 = zeros(3x1,0nz) */
  /* #295: @1 = zeros(3x1) */
  casadi_clear(w01, 3);
  /* #296: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #297: @23 = ones(10x1,1nz) */
  w23 = 1.;
  /* #298: {NULL, NULL, @32} = vertsplit(@23) */
  w32 = w23;
  /* #299: @23 = @32[0] */
  for (rr=(&w23), cs=(&w32)+0; cs!=(&w32)+1; cs+=1) *rr++ = *cs;
  /* #300: @9 = (@9*@23) */
  w09 *= w23;
  /* #301: @9 = (-@9) */
  w09 = (- w09 );
  /* #302: @23 = @32[0] */
  for (rr=(&w23), cs=(&w32)+0; cs!=(&w32)+1; cs+=1) *rr++ = *cs;
  /* #303: @13 = (@13*@23) */
  w13 *= w23;
  /* #304: @13 = (-@13) */
  w13 = (- w13 );
  /* #305: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #306: @23 = @32[0] */
  for (rr=(&w23), cs=(&w32)+0; cs!=(&w32)+1; cs+=1) *rr++ = *cs;
  /* #307: @15 = (@15*@23) */
  w15 *= w23;
  /* #308: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #309: @0 = horzcat(@9, @13, @15) */
  rr=w00;
  *rr++ = w09;
  *rr++ = w13;
  *rr++ = w15;
  /* #310: @0 = @0' */
  /* #311: @9 = @32[0] */
  for (rr=(&w09), cs=(&w32)+0; cs!=(&w32)+1; cs+=1) *rr++ = *cs;
  /* #312: @20 = (@20*@9) */
  w20 *= w09;
  /* #313: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #314: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #315: @9 = @32[0] */
  for (rr=(&w09), cs=(&w32)+0; cs!=(&w32)+1; cs+=1) *rr++ = *cs;
  /* #316: @26 = (@26*@9) */
  w26 *= w09;
  /* #317: @26 = (-@26) */
  w26 = (- w26 );
  /* #318: @9 = @32[0] */
  for (rr=(&w09), cs=(&w32)+0; cs!=(&w32)+1; cs+=1) *rr++ = *cs;
  /* #319: @27 = (@27*@9) */
  w27 *= w09;
  /* #320: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #321: @33 = horzcat(@20, @26, @27) */
  rr=w33;
  *rr++ = w20;
  *rr++ = w26;
  *rr++ = w27;
  /* #322: @33 = @33' */
  /* #323: @20 = @32[0] */
  for (rr=(&w20), cs=(&w32)+0; cs!=(&w32)+1; cs+=1) *rr++ = *cs;
  /* #324: @17 = (@17*@20) */
  w17 *= w20;
  /* #325: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #326: @20 = @32[0] */
  for (rr=(&w20), cs=(&w32)+0; cs!=(&w32)+1; cs+=1) *rr++ = *cs;
  /* #327: @38 = (@38*@20) */
  w38 *= w20;
  /* #328: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #329: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #330: @20 = @32[0] */
  for (rr=(&w20), cs=(&w32)+0; cs!=(&w32)+1; cs+=1) *rr++ = *cs;
  /* #331: @44 = (@44*@20) */
  w44 *= w20;
  /* #332: @46 = horzcat(@17, @38, @44) */
  rr=w46;
  *rr++ = w17;
  *rr++ = w38;
  *rr++ = w44;
  /* #333: @46 = @46' */
  /* #334: @51 = horzcat(@0, @33, @46) */
  rr=w51;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  /* #335: @1 = mac(@51,@3,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w51+j, ct=w03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #336: @1 = (@2*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #337: @48 = zeros(4x1) */
  casadi_clear(w48, 4);
  /* #338: @48 = mac(@49,@32,@48) */
  casadi_mtimes(w49, casadi_s2, (&w32), casadi_s9, w48, casadi_s0, w, 0);
  /* #339: @64 = vertcat(@61, @1, @48) */
  rr=w64;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<4; ++i) *rr++ = *cs++;
  /* #340: @65 = @64[:7] */
  for (rr=w65, cs=w64+0; cs!=w64+7; cs+=1) *rr++ = *cs;
  /* #341: (@58[10, 15, 20, 24, 28, 32, 36] = @65) */
  for (cii=casadi_s10, rr=w58, cs=w65; cii!=casadi_s10+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #342: @66 = @58' */
  casadi_trans(w58,casadi_s12, w66, casadi_s11, iw);
  /* #343: @67 = input[5][0] */
  wr67 = arg[5] ? arg[5] : casadi_zeros;
  /* #344: @57 = mac(@66,@67,@57) */
  casadi_mtimes(w66, casadi_s11, wr67, casadi_s13, w57, casadi_s13, w, 0);
  /* #345: @56 = mac(@57,@58,@56) */
  casadi_mtimes(w57, casadi_s13, w58, casadi_s12, w56, casadi_s13, w, 0);
  /* #346: @32 = input[4][0] */
  w32 = arg[4] ? arg[4][0] : 0;
  /* #347: @17 = 4 */
  w17 = 4.;
  /* #348: @17 = pow(@2,@17) */
  w17  = pow(w02,w17);
  /* #349: @17 = (@32*@17) */
  w17  = (w32*w17);
  /* #350: @1 = @17[0, 0, 0] */
  for (cii=casadi_s14, rr=w01, cs=(&w17); cii!=casadi_s14+3; ++cii) *rr++ = cs[*cii];
  /* #351: @51 = zeros(3x3) */
  casadi_clear(w51, 9);
  /* #352: @53 = zeros(3x4) */
  casadi_clear(w53, 12);
  /* #353: @68 = horzcat(@1, @51, @53) */
  rr=w68;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w51; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<12; ++i) *rr++ = *cs++;
  /* #354: @69 = @68' */
  casadi_trans(w68,casadi_s16, w69, casadi_s15, iw);
  /* #355: @51 = zeros(3x3) */
  casadi_clear(w51, 9);
  /* #356: @17 = sq(@2) */
  w17 = casadi_sq( w02 );
  /* #357: @32 = (@32*@17) */
  w32 *= w17;
  /* #358: @1 = @32[0, 0, 0] */
  for (cii=casadi_s14, rr=w01, cs=(&w32); cii!=casadi_s14+3; ++cii) *rr++ = cs[*cii];
  /* #359: @53 = zeros(3x4) */
  casadi_clear(w53, 12);
  /* #360: @68 = horzcat(@51, @1, @53) */
  rr=w68;
  for (i=0, cs=w51; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<12; ++i) *rr++ = *cs++;
  /* #361: @70 = @68' */
  casadi_trans(w68,casadi_s18, w70, casadi_s17, iw);
  /* #362: @53 = zeros(4x3) */
  casadi_clear(w53, 12);
  /* #363: @52 = zeros(4x3) */
  casadi_clear(w52, 12);
  /* #364: @49 = zeros(4x4) */
  casadi_clear(w49, 16);
  /* #365: @32 = 2 */
  w32 = 2.;
  /* #366: @2 = (@2/@32) */
  w02 /= w32;
  /* #367: @48 = zeros(4x1) */
  casadi_clear(w48, 4);
  /* #368: @1 = @4[1:4] */
  for (rr=w01, cs=w04+1; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #369: @1 = @1' */
  /* #370: @1 = (-@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) *rr++ = (- *cs++ );
  /* #371: @1 = @1' */
  /* #372: @3 = @4[0, 0, 0] */
  for (cii=casadi_s14, rr=w03, cs=w04; cii!=casadi_s14+3; ++cii) *rr++ = cs[*cii];
  /* #373: @51 = dense(@3) */
  casadi_densify(w03, casadi_s19, w51, 0);
  /* #374: @32 = 0 */
  w32 = 0.;
  /* #375: @17 = @4[3] */
  for (rr=(&w17), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #376: @17 = (-@17) */
  w17 = (- w17 );
  /* #377: @38 = @4[2] */
  for (rr=(&w38), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #378: @3 = horzcat(@32, @17, @38) */
  rr=w03;
  *rr++ = w32;
  *rr++ = w17;
  *rr++ = w38;
  /* #379: @3 = @3' */
  /* #380: @32 = @4[3] */
  for (rr=(&w32), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #381: @17 = 0 */
  w17 = 0.;
  /* #382: @38 = @4[1] */
  for (rr=(&w38), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #383: @38 = (-@38) */
  w38 = (- w38 );
  /* #384: @0 = horzcat(@32, @17, @38) */
  rr=w00;
  *rr++ = w32;
  *rr++ = w17;
  *rr++ = w38;
  /* #385: @0 = @0' */
  /* #386: @32 = @4[2] */
  for (rr=(&w32), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #387: @32 = (-@32) */
  w32 = (- w32 );
  /* #388: @17 = @4[1] */
  for (rr=(&w17), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #389: @38 = 0 */
  w38 = 0.;
  /* #390: @33 = horzcat(@32, @17, @38) */
  rr=w33;
  *rr++ = w32;
  *rr++ = w17;
  *rr++ = w38;
  /* #391: @33 = @33' */
  /* #392: @47 = horzcat(@3, @0, @33) */
  rr=w47;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  /* #393: @71 = @47' */
  for (i=0, rr=w71, cs=w47; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #394: @51 = (@51+@71) */
  for (i=0, rr=w51, cs=w71; i<9; ++i) (*rr++) += (*cs++);
  /* #395: @71 = @51' */
  for (i=0, rr=w71, cs=w51; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #396: @72 = horzcat(@1, @71) */
  rr=w72;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w71; i<9; ++i) *rr++ = *cs++;
  /* #397: @73 = @72' */
  for (i=0, rr=w73, cs=w72; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #398: @32 = input[3][0] */
  w32 = arg[3] ? arg[3][0] : 0;
  /* #399: @17 = sqrt(@32) */
  w17 = sqrt( w32 );
  /* #400: @38 = sqrt(@32) */
  w38 = sqrt( w32 );
  /* #401: @32 = sqrt(@32) */
  w32 = sqrt( w32 );
  /* #402: @1 = vertcat(@17, @38, @32) */
  rr=w01;
  *rr++ = w17;
  *rr++ = w38;
  *rr++ = w32;
  /* #403: @48 = mac(@73,@1,@48) */
  for (i=0, rr=w48; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w73+j, ct=w01+i*3; k<3; ++k) *rr += cs[k*4]**ct++;
  /* #404: @48 = (@2*@48) */
  for (i=0, rr=w48, cs=w48; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #405: @48 = (-@48) */
  for (i=0, rr=w48, cs=w48; i<4; ++i) *rr++ = (- *cs++ );
  /* #406: @4 = @48' */
  casadi_copy(w48, 4, w04);
  /* #407: @49 = mac(@48,@4,@49) */
  for (i=0, rr=w49; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w48+j, ct=w04+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #408: @74 = horzcat(@53, @52, @49) */
  rr=w74;
  for (i=0, cs=w53; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<16; ++i) *rr++ = *cs++;
  /* #409: @75 = @74' */
  for (i=0, rr=w75, cs=w74; i<10; ++i) for (j=0; j<4; ++j) rr[i+j*10] = *cs++;
  /* #410: @76 = horzcat(@69, @70, @75) */
  rr=w76;
  for (i=0, cs=w69; i<24; ++i) *rr++ = *cs++;
  for (i=0, cs=w70; i<24; ++i) *rr++ = *cs++;
  for (i=0, cs=w75; i<40; ++i) *rr++ = *cs++;
  /* #411: @77 = @76' */
  casadi_trans(w76,casadi_s20, w77, casadi_s20, iw);
  /* #412: @57 = dense(@77) */
  casadi_densify(w77, casadi_s20, w57, 0);
  /* #413: @56 = (@56+@57) */
  for (i=0, rr=w56, cs=w57; i<100; ++i) (*rr++) += (*cs++);
  /* #414: output[1][0] = @56 */
  casadi_copy(w56, 100, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int ekf_predict(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ekf_predict_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ekf_predict_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ekf_predict_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ekf_predict_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ekf_predict_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ekf_predict_incref(void) {
}

CASADI_SYMBOL_EXPORT void ekf_predict_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ekf_predict_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int ekf_predict_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real ekf_predict_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ekf_predict_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ekf_predict_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ekf_predict_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s21;
    case 1: return casadi_s22;
    case 2: return casadi_s22;
    case 3: return casadi_s21;
    case 4: return casadi_s21;
    case 5: return casadi_s23;
    case 6: return casadi_s24;
    case 7: return casadi_s22;
    case 8: return casadi_s22;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ekf_predict_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s25;
    case 1: return casadi_s23;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ekf_predict_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 11;
  if (sz_w) *sz_w = 942;
  return 0;
}

CASADI_SYMBOL_EXPORT int ekf_predict_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 11*sizeof(casadi_int);
  if (sz_w) *sz_w = 942*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
