
#pragma once

/* Full 10-state EKF implementation of state estimation
 *
 * Position (3-state)
 * Velocity (3-state)
 * Attitude (4-state quaternion)
 *
 * We integrate accelerometer readings for position/velocity estimation and gyrometer
 * readings for attitude estimation.
 *
 * Correction is done using GPS for position/velocity and magnetometer & accelerometer
 * reference vectors for the attitude correction.
 *
 * All EKF inputs should be expressed in an ENU frame. Similarly, the output state
 * vector is expressed in an ENU frame.
 *
 *
 * Part 1. Predict
 * This function returns a predicted state (float[10]) and predicted covariance matrix (float[10][10])
 *
 * Part 2. Correct
 * This function returns a measurement corrected state matrix and covariance matrix
 *
 */

#include <AP_Math.h>

#include "mcstate_interface.h"

#define EKF_DATA_TYPE float
#define EKF_STATE_SIZE 16
#define EKF_COVARIANCE_SIZE 16

#define EKF_FUSE_ACC 1
#define EKF_FUSE_MAG 1
#define EKF_FUSE_GPS 1
#define EKF_FUSE_BARO 1

class StateEKF : public MCState {
	public:
		StateEKF(void) : MCState() { }

	private:
		/* @brief Prepare correct and predict arguments vectors */
		void setup_ekf_args(void);

		/* @brief Internal reset method */
		void reset(void);

	private:
		/* Our casadi functions use the following interface:
		 *
		 *
		 *
		 */

		// EKF arguments and result matrices
		
		// Time Step
		EKF_DATA_TYPE dt;

		// Gyrometer
		EKF_DATA_TYPE w[3];
		EKF_DATA_TYPE var_gyro;

		// Accelerometer
		EKF_DATA_TYPE a[3];
		EKF_DATA_TYPE var_accel;

		// Magnetometer
		EKF_DATA_TYPE m[3];
		EKF_DATA_TYPE var_mag;

		// GPS
		EKF_DATA_TYPE gps_pos[3];
		EKF_DATA_TYPE gps_vel[3];
		EKF_DATA_TYPE var_gps_pos;
		EKF_DATA_TYPE var_gps_vel;

		// Barometer
		EKF_DATA_TYPE barometer_altitude;
		EKF_DATA_TYPE var_barometer;

		// State
		EKF_DATA_TYPE q[4];
		EKF_DATA_TYPE x[3];
		EKF_DATA_TYPE v[3];
		EKF_DATA_TYPE drift_gyro[3];
		EKF_DATA_TYPE drift_acc[3];

		//EKF_DATA_TYPE cov[ EKF_COVARIANCE_SIZE * EKF_COVARIANCE_SIZE ];

		// Output states (from each fusion function)
		EKF_DATA_TYPE state_out[ EKF_STATE_SIZE ];
		EKF_DATA_TYPE cov_out[ EKF_COVARIANCE_SIZE * EKF_COVARIANCE_SIZE ];

		// Input states
		EKF_DATA_TYPE state_est[ EKF_STATE_SIZE ];
		EKF_DATA_TYPE cov_est[ EKF_COVARIANCE_SIZE * EKF_COVARIANCE_SIZE ];

		EKF_DATA_TYPE* ekf_predict_arg[9] = {
			&dt,
			w,
			a,
			&var_gyro,
			&var_accel,
			cov, 
			q,
			x,
			v};

		EKF_DATA_TYPE* ekf_predict_res[2] = {state_est, cov_est};


		// TODO These kgain and vt matrices are wrong size as they are different for each fusion
		// vt is (12,1) and kgain is (10,12)
		EKF_DATA_TYPE vt[12];
		EKF_DATA_TYPE kgain[120];


		/* 1. Accelerometer Fusion */
		EKF_DATA_TYPE* ekf_fuse_acc_arg[4] = {
			a,
			&var_accel,
			state_est,
			cov_est
		};

		EKF_DATA_TYPE* ekf_fuse_acc_res[4] = {state_out, cov_out, vt, kgain};

		/* 2. Magnetometer Fusion */
		EKF_DATA_TYPE* ekf_fuse_mag_arg[4] = {
			m,
			&var_mag,
			state_est,
			cov_est
		};

		EKF_DATA_TYPE* ekf_fuse_mag_res[4] = {state_out, cov_out, vt, kgain};

		/* 3. GPS Fusion */
		EKF_DATA_TYPE* ekf_fuse_gps_arg[6] = {
			gps_pos,
			gps_vel,
			&var_gps_pos,
			&var_gps_vel,
			state_est,
			cov_est
		};

		EKF_DATA_TYPE* ekf_fuse_gps_res[4] = {state_out, cov_out, vt, kgain};

		/* 4. Barometer Fusion */
		EKF_DATA_TYPE* ekf_fuse_baro_arg[4] = {
			&barometer_altitude,
			&var_barometer,
			state_est,
			cov_est
		};

		EKF_DATA_TYPE* ekf_fuse_baro_res[4] = {state_out, cov_out, vt, kgain};

	public:

		/* @brief Run full update of EKF predict/correct for attitude and inertial navigation */
		void update(void) override;

		/* @brief Initialise EKF */
		void init_derived(void) override;

	private:

		// NOTE These are wrapper functions around the correct c-function generated by casadi in the EKF python notebook
		// Each of these wrappers needs to setup the input matrices and then call the generated function

		void ekf_predict(void);

		void ekf_fuse_acc(void);

		void ekf_fuse_mag(void);

		void ekf_fuse_gps(void);

		void ekf_fuse_baro(void);


};


